name: Post Merge

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

concurrency: webhooks-post-merge

jobs:
  pr:
    uses: ./.github/workflows/run-tests.yml

  publish-webhooks-consumer-contract-tests:
    needs: pr
    runs-on: ubuntu-latest

    name: Publish and tag webhooks consumer pact
    steps:
      - name: Git checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - name: Set up JDK 17
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache pacts directory
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: target/pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Publish and tag webhooks consumer pact
        run: |
          mvn pact:publish -DPACT_BROKER_URL=https://pay-pact-broker.cloudapps.digital \
          -DPACT_BROKER_USERNAME=${{ secrets.pact_broker_username }} \
          -DPACT_BROKER_PASSWORD=${{ secrets.pact_broker_password }} -DPACT_CONSUMER_TAG=master \
          -DPACT_CONSUMER_VERSION=${{ github.sha }}

  ledger-provider-contract-tests:
    needs: publish-webhooks-consumer-contract-tests
    uses: alphagov/pay-ledger/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: webhooks
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  tag-release:
    needs:
      - pr
      - ledger-provider-contract-tests
    permissions:
      contents: write
    uses: alphagov/pay-ci/.github/workflows/_create-alpha-release-tag.yml@master
