name: Test Pull Request

on: pull_request

permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Set up JDK 17
        uses: actions/setup-java@4fe61d24fe5472910b93bdeffb8aad49f979d862
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests
        run: mvn clean verify
      - name: Upload Artifact
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: target
          path: target
          retention-days: 5
