name: Main merge test and tag

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

concurrency: webhooks-post-merge

jobs:
  pr:
    uses: ./.github/workflows/pr.yml

  publish-webhooks-consumer-contract-tests:
    needs: pr
    runs-on: ubuntu-18.04

    name: Publish and tag webhooks consumer pact
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - name: Set up JDK 17
        uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache pacts directory
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0
        with:
          path: target/pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Publish and tag webhooks consumer pact
        run: |
          mvn pact:publish -DPACT_BROKER_URL=https://pay-pact-broker.cloudapps.digital \
          -DPACT_BROKER_USERNAME=${{ secrets.pact_broker_username }} \
          -DPACT_BROKER_PASSWORD=${{ secrets.pact_broker_password }} -DPACT_CONSUMER_TAG=master \
          -DPACT_CONSUMER_VERSION=${{ github.sha }}

  ledger-provider-contract-tests:
    needs: publish-webhooks-consumer-contract-tests
    uses: alphagov/pay-ledger/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: webhooks
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  tag-release:
    needs:
      - pr
      - ledger-provider-contract-tests
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: '0'
      - name: Tag release
        run: |
          LATEST_RELEASE_NUMBER=$(git describe --abbrev=0 --tags --match "alpha_release-*" | awk -F- '{print $2}' || true)
          number_regex='^[0-9]+$'
          if ! [[ ${LATEST_RELEASE_NUMBER} =~ $number_regex ]]; then
           LATEST_RELEASE_NUMBER=0
          fi
          NEW_RELEASE_NUMBER=$((LATEST_RELEASE_NUMBER + 1))
          TAG_NAME=alpha_release-${NEW_RELEASE_NUMBER}
          echo "TAG_NAME: ${TAG_NAME}"

          git config user.email payments-team@digital.cabinet-office.gov.uk
          git config user.name pay-github-actions
          DATE=$(date +%Y-%m-%d:%H:%M:%S)
          git tag -a ${TAG_NAME} ${GITHUB_SHA} -m "Release candidate tag created on ${DATE}"
          git push origin --tags
