name: Main merge test and tag

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: '0'
      - name: Set up JDK 17
        uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests
        run: mvn clean verify
      - name: Upload jar
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: target
          path: target
          retention-days: 5
  tag-release:
    needs: test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: '0'
      - name: Tag release
        run: |
          LATEST_RELEASE_NUMBER=$(git describe --abbrev=0 --tags --match "alpha_release-*" | awk -F- '{print $2}' || true)
          number_regex='^[0-9]+$'
          if ! [[ ${LATEST_RELEASE_NUMBER} =~ $number_regex ]]; then
           LATEST_RELEASE_NUMBER=0
          fi
          NEW_RELEASE_NUMBER=$((LATEST_RELEASE_NUMBER + 1))
          TAG_NAME=alpha_release-${NEW_RELEASE_NUMBER}
          echo "TAG_NAME: ${TAG_NAME}"

          git config user.email payments-team@digital.cabinet-office.gov.uk
          git config user.name pay-github-actions
          DATE=$(date +%Y-%m-%d:%H:%M:%S)
          git tag -a ${TAG_NAME} ${GITHUB_SHA} -m "Release candidate tag created on ${DATE}"
          git push origin --tags
